name: Build and push Docker images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    strategy:
      matrix:
        include:
          - toolchain: gcc
            version: 11
          - toolchain: gcc
            version: 12
          - toolchain: gcc
            version: 9-centos
          - toolchain: gcc
            version: 13
          - toolchain: gcc
            version: 13-alpine
          - toolchain: gcc
            version: 14
          - toolchain: gcc
            version: 14-rhel-ubi9
          - toolchain: clang
            version: 19
          - toolchain: clang
            version: 20
          - toolchain: oneapi
            version: 2024.2.0-rhel-ubi9
          - toolchain: oneapi
            version: 2025.1.1-rhel-ubi9

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}:${{ matrix.toolchain }}${{ matrix.version }}
      IMAGE_ROOT: ${{ github.workspace }}/${{ matrix.toolchain }}/${{ matrix.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Build Docker image
        run: |
          cd ${GITHUB_WORKSPACE}/${{ matrix.toolchain }}/${{ matrix.version }}
          docker build -t ${REGISTRY}/${IMAGE_NAME} -f Dockerfile .
      
      - name: Log in to the Container registry
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        if: ${{ github.ref == 'refs/heads/main' }}
        id: push
        run: |
          docker push ${REGISTRY}/${IMAGE_NAME}
